### ISSUE TITLE
no synth or sample named 'vst' could be found. module 'sound': instrument not found: vst

### ISSUE THREAD

**Issue by jarmitage** [thgrund/TidalVST#2]
If I run the code as is, I get the following error in SuperCollider when running `d1 $ n 0 # vst "myVst"` in Tidal:

```
no synth or sample named 'vst' could be found.
module 'sound': instrument not found: vst
```

In `TidalVST.scd`, the `SynthDef` is defined like this:

https://github.com/thgrund/TidalVST/blob/3159f06049a17085653a763f01c22cacf2ed9d93/TidalVST.scd#L2-L4

I can't see a `SynthDef(\vst, ...` defined anywhere, so the above error message seems to make sense.

What am I missing here?

**Comment by thgrund** [comment]
Sorry for the late reply. I tried it today and indeed you missed something (but it was not clear mentioned in the README). 
You need to execute this statement in TidalCycles before you can use the `vst` statement: 

```
vstName = pS "vstName"
vst name = s "vst" # vstName name
```

It is defined in this file: https://github.com/thgrund/TidalVST/blob/main/newFunctions.hs

Let me know if there is any further problem.

**Comment by jarmitage** [comment]
Thanks for taking a look!

I already had this defined on the Tidal side, the `no synth or sample named 'vst' could be found` error was happening on the SuperCollider side.

But I'm guessing this would be fixed by bringing TidalVST in line with the latest SuperDirt?

**Comment by thgrund** [comment]
This error message on SuperCollider side is confusing but I was not able to suppress it. It shouldn't affect the functionality of the TidalVST (but I am aware of this).

**Comment by jarmitage** [comment]
I see, I was slightly confused about whether this is what you were referring to in the README, but this confirms it, thanks.

I will test again to see if it's actually working.

**Comment by thgrund** [comment]
This issue should be closed because with the current implementation you can just use the `s` function with a custom name and access the vst without having this error message.
